Join as user to league
on-full-hack/rankr-backend pull request #8
Opened 2019-04-24 21:20 UTC by lwypchal

2019-04-25 09:12 UTC, dawhey requested changes
@lwypchal review done ⚡️

2019-04-25 09:12 UTC, dawhey commented on src/main/java/pl/on/full/hack/league/controller/LeagueController.java
> +    public ResponseEntity<BaseApiContract<String>> joinToLeague(@PathVariable("league_id") Long league_id, Authentication authentication) {
`Long league_id` w javie zmienne camelCasem :D

2019-04-25 09:12 UTC, dawhey commented on src/main/java/pl/on/full/hack/league/service/LeaguePlayerService.java
> +    public String joinToLeague(final Long league_id, final String username) throws NotFoundException, Exception{
lepiej dodać adnotację `@NonNull` z lomboka niż robić nullchecki

2019-04-25 09:12 UTC, dawhey commented on src/main/java/pl/on/full/hack/league/service/LeaguePlayerService.java
> +            if(checkIfPlayerExists.isPresent()){ throw new Exception ("Player actually is waiting for accept in league"); }
tu możesz zrobić nową klasę dziedziczącą po `RuntimeException` np. `PendingRequestException` i rzucić w kontrolerze status 202 (czyli accepted/pending)

2019-04-25 09:12 UTC, dawhey commented on src/main/java/pl/on/full/hack/league/service/LeaguePlayerService.java
> +            repository.save(player);
W serwisie nie powinno być logiki mapującej. Stworzyć kontruktor z argumentami/użyć `@Builder` z Lomboka i przenieść inicjalizację gdzieś do innej funkcji

2019-04-25 22:13 UTC, lwypchal commented on src/main/java/pl/on/full/hack/league/service/LeaguePlayerService.java
> +            repository.save(player);
@Builder ma wplyw negatywny na @Entity wiec ten sposob odpada...

2019-04-26 09:54 UTC, dawhey approved these changes

2019-04-26 09:55 UTC, dawhey commented
@lwypchal  dobra robota mordooooo

2019-04-26 09:55 UTC, merged